// <auto-generated />
using System;
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(TaxiBookingContext))]
    [Migration("20230419065233_updatedatabase")]
    partial class updatedatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLayer.Entity.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("date");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Pincode")
                        .HasColumnType("varchar(6)");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BookingStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DropOffTime")
                        .HasColumnType("datetime");

                    b.Property<string>("DropoffLocation")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("date");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("PickupDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PickupLocation")
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("RatingId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VehiclePreference")
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BookingStatusId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DriverId");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("PaymentId")
                        .IsUnique()
                        .HasFilter("[PaymentId] IS NOT NULL");

                    b.HasIndex("RatingId")
                        .IsUnique()
                        .HasFilter("[RatingId] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.BookingStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("date");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(15)");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("BookingStatuses");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.CancellationReason", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("date");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("CancellationReasons");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.CancelledBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("date");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("ReasonId")
                        .HasColumnType("int");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("isPending")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("ReasonId");

                    b.ToTable("CancelledBookings");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("date");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(30)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("StateId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("DrivingLicense")
                        .HasColumnType("varchar(15)");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("date");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("decimal");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.Property<bool>("isApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy")
                        .IsUnique()
                        .HasFilter("[CreatedBy] IS NOT NULL");

                    b.HasIndex("LocationId")
                        .IsUnique()
                        .HasFilter("[LocationId] IS NOT NULL");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("VehicleId")
                        .IsUnique()
                        .HasFilter("[VehicleId] IS NOT NULL");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Lattitude")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("date");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Payment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ModeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("date");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("date")
                        .HasColumnType("date");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModeId");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.PaymentMode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Mode")
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("date");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("PaymentModes");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("date");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("Ratings")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DriverId");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("date");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("date");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("States");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.User", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("FirstName")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Gender")
                        .HasColumnType("varchar(6)");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("date");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("varchar(MAX)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.VehicleDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("date");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("RegistrationName")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Seating")
                        .HasColumnType("int");

                    b.Property<string>("VehicleModel")
                        .HasColumnType("varchar(20)");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("isApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("VehicleDetails");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.VehicleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("date");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("VehicleTypes");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Area", b =>
                {
                    b.HasOne("DataAccessLayer.Entity.City", "City")
                        .WithMany("Areas")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entity.User", "Created")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entity.User", "Modified")
                        .WithMany()
                        .HasForeignKey("ModifiedBy");

                    b.Navigation("City");

                    b.Navigation("Created");

                    b.Navigation("Modified");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Booking", b =>
                {
                    b.HasOne("DataAccessLayer.Entity.BookingStatus", "BookingStatus")
                        .WithMany("Bookings")
                        .HasForeignKey("BookingStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataAccessLayer.Entity.User", "Created")
                        .WithOne("Booking")
                        .HasForeignKey("DataAccessLayer.Entity.Booking", "CreatedBy");

                    b.HasOne("DataAccessLayer.Entity.Driver", "Driver")
                        .WithMany("Bookings")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataAccessLayer.Entity.User", "Modified")
                        .WithMany()
                        .HasForeignKey("ModifiedBy");

                    b.HasOne("DataAccessLayer.Entity.Payment", "Payment")
                        .WithOne("Booking")
                        .HasForeignKey("DataAccessLayer.Entity.Booking", "PaymentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataAccessLayer.Entity.Rating", "Rating")
                        .WithOne("Booking")
                        .HasForeignKey("DataAccessLayer.Entity.Booking", "RatingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataAccessLayer.Entity.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BookingStatus");

                    b.Navigation("Created");

                    b.Navigation("Driver");

                    b.Navigation("Modified");

                    b.Navigation("Payment");

                    b.Navigation("Rating");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.BookingStatus", b =>
                {
                    b.HasOne("DataAccessLayer.Entity.User", "Created")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entity.User", "Modified")
                        .WithMany()
                        .HasForeignKey("ModifiedBy");

                    b.Navigation("Created");

                    b.Navigation("Modified");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.CancellationReason", b =>
                {
                    b.HasOne("DataAccessLayer.Entity.User", "Created")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entity.User", "Modified")
                        .WithMany()
                        .HasForeignKey("ModifiedBy");

                    b.Navigation("Created");

                    b.Navigation("Modified");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.CancelledBooking", b =>
                {
                    b.HasOne("DataAccessLayer.Entity.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entity.User", "Created")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entity.User", "Modified")
                        .WithMany()
                        .HasForeignKey("ModifiedBy");

                    b.HasOne("DataAccessLayer.Entity.CancellationReason", "CancellationReason")
                        .WithMany("CancelledBookings")
                        .HasForeignKey("ReasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("CancellationReason");

                    b.Navigation("Created");

                    b.Navigation("Modified");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.City", b =>
                {
                    b.HasOne("DataAccessLayer.Entity.User", "Created")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entity.User", "Modified")
                        .WithMany()
                        .HasForeignKey("ModifiedBy");

                    b.HasOne("DataAccessLayer.Entity.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Created");

                    b.Navigation("Modified");

                    b.Navigation("State");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Driver", b =>
                {
                    b.HasOne("DataAccessLayer.Entity.User", "Created")
                        .WithOne("CreatedDriver")
                        .HasForeignKey("DataAccessLayer.Entity.Driver", "CreatedBy");

                    b.HasOne("DataAccessLayer.Entity.Location", "Location")
                        .WithOne("Driver")
                        .HasForeignKey("DataAccessLayer.Entity.Driver", "LocationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DataAccessLayer.Entity.User", "Modified")
                        .WithMany()
                        .HasForeignKey("ModifiedBy");

                    b.HasOne("DataAccessLayer.Entity.User", "User")
                        .WithOne("Driver")
                        .HasForeignKey("DataAccessLayer.Entity.Driver", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entity.VehicleDetail", "VehicleDetail")
                        .WithOne("Driver")
                        .HasForeignKey("DataAccessLayer.Entity.Driver", "VehicleId");

                    b.Navigation("Created");

                    b.Navigation("Location");

                    b.Navigation("Modified");

                    b.Navigation("User");

                    b.Navigation("VehicleDetail");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Location", b =>
                {
                    b.HasOne("DataAccessLayer.Entity.Area", "Area")
                        .WithMany("Locations")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entity.User", "Created")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entity.User", "Modified")
                        .WithMany()
                        .HasForeignKey("ModifiedBy");

                    b.Navigation("Area");

                    b.Navigation("Created");

                    b.Navigation("Modified");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Payment", b =>
                {
                    b.HasOne("DataAccessLayer.Entity.User", "Created")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entity.PaymentMode", "PaymentMode")
                        .WithMany("Payments")
                        .HasForeignKey("ModeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entity.User", "Modified")
                        .WithMany()
                        .HasForeignKey("ModifiedBy");

                    b.Navigation("Created");

                    b.Navigation("Modified");

                    b.Navigation("PaymentMode");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.PaymentMode", b =>
                {
                    b.HasOne("DataAccessLayer.Entity.User", "Created")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entity.User", "Modified")
                        .WithMany()
                        .HasForeignKey("ModifiedBy");

                    b.Navigation("Created");

                    b.Navigation("Modified");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Rating", b =>
                {
                    b.HasOne("DataAccessLayer.Entity.User", "Created")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entity.Driver", "Driver")
                        .WithMany("Ratings")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entity.User", "Modified")
                        .WithMany()
                        .HasForeignKey("ModifiedBy");

                    b.Navigation("Created");

                    b.Navigation("Driver");

                    b.Navigation("Modified");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Role", b =>
                {
                    b.HasOne("DataAccessLayer.Entity.User", "Created")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("DataAccessLayer.Entity.User", "Modified")
                        .WithMany()
                        .HasForeignKey("ModifiedBy");

                    b.Navigation("Created");

                    b.Navigation("Modified");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.State", b =>
                {
                    b.HasOne("DataAccessLayer.Entity.User", "Created")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entity.User", "Modified")
                        .WithMany()
                        .HasForeignKey("ModifiedBy");

                    b.Navigation("Created");

                    b.Navigation("Modified");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.User", b =>
                {
                    b.HasOne("DataAccessLayer.Entity.User", "Created")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("DataAccessLayer.Entity.User", "Modified")
                        .WithMany()
                        .HasForeignKey("ModifiedBy");

                    b.HasOne("DataAccessLayer.Entity.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Created");

                    b.Navigation("Modified");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.VehicleDetail", b =>
                {
                    b.HasOne("DataAccessLayer.Entity.User", "Created")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entity.User", "Modified")
                        .WithMany()
                        .HasForeignKey("ModifiedBy");

                    b.HasOne("DataAccessLayer.Entity.VehicleType", "VehicleType")
                        .WithMany("VehicleDetails")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Created");

                    b.Navigation("Modified");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.VehicleType", b =>
                {
                    b.HasOne("DataAccessLayer.Entity.User", "Created")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entity.User", "Modified")
                        .WithMany()
                        .HasForeignKey("ModifiedBy");

                    b.Navigation("Created");

                    b.Navigation("Modified");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Area", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.BookingStatus", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.CancellationReason", b =>
                {
                    b.Navigation("CancelledBookings");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.City", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Driver", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Location", b =>
                {
                    b.Navigation("Driver");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Payment", b =>
                {
                    b.Navigation("Booking");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.PaymentMode", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Rating", b =>
                {
                    b.Navigation("Booking");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.State", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.User", b =>
                {
                    b.Navigation("Booking");

                    b.Navigation("Bookings");

                    b.Navigation("CreatedDriver");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.VehicleDetail", b =>
                {
                    b.Navigation("Driver");
                });

            modelBuilder.Entity("DataAccessLayer.Entity.VehicleType", b =>
                {
                    b.Navigation("VehicleDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
